### ISSUE TITLE
Add font mixin

### ISSUE THREAD

**Issue by Miilkytea** [BitsBytesAI/feminist_ai_projects#19]
https://gist.github.com/jonathantneal/d0460e5c2d5d7f9bc5e6
http://stackoverflow.com/questions/18294150/how-to-use-fonts-in-rails-4
http://aokolish.me/blog/2011/12/24/at-font-face-with-the-asset-pipeline/

#### @Miilkytea  added this line to **`config/application.rb`** per the instructions in [this tutorial.](http://aokolish.me/blog/2011/12/24/at-font-face-with-the-asset-pipeline/)
```ruby
config.assets.paths << Rails.root.join("app", "assets", "fonts")
```

Which returns this Error:
```bash
config/application.rb:27:in `<top (required)>': undefined local variable or method `config' for main:Object (NameError)
```
# Commit c9da34004dad71330d8c4bfa617064851703aa70

---

#### Possible problem:
It seems strange to me that that GT America Directory and all of the fonts have spaces in their names ie: `app/assets/font/GT America/GT America Compressed Bold Italic.otf`

???? @Miilkytea  I'm not sure how to add these fonts.  
Where did they come from?  
Is there a license for these?  
Have you added external fonts before?  

Any help or advise @paulaburke ?

**Comment by jendiamond** [comment]
Not sure how to add these fonts.

It seems strange to me that that GT America Directory and all of the fonts have spaces in their names ie: `app/assets/font/GT America/GT America Compressed Bold Italic.otf`

**Comment by jendiamond** [comment]
My next thought is "what is font face?"   
All the directions I Googled about "Add outside font to Rails" mentions adding @font-face.

### My explorations of font-face:
On the official Font Face site: http://www.font-face.com/#green_content
There is a section called: How do i use @font-face. It reads:

>Initially you define the rule, "font-family" is what you want to call the font, "src" is where it can be found, include a "font-weight" (not needed for normal, but required by everything else, bold, thin etc).
```
@font-face {
    font-family: DeliciousRoman;
    src: url(http://www.font-face.com/fonts/delicious/Delicious-Roman.otf);
    font-weight:400;
}
>Then just use it like any other font in any other style rule.
```
p {
    font-family: DeliciousRoman, Helvetica, Arial, sans-serif;
}
```

[This site](https://css-tricks.com/snippets/css/using-font-face/) wasn't that helpful but the comments may lead in a direction:
 
### Eddie says:  
Just as a suggestion, i think you should use the [Paul Irish Bulletproof Method](https://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/). This seems to be a more direct, quicker (less HTTP requests) format. Example:
```
@font-face {
  font-family: Delicious;
  src: url(Delicious-Roman.eot);
  src: local('Delicious'), local(Delicious'), 
         url(Delicious-Roman.otf) format('opentype');
}
```

### Micah says:  
Permalink to comment# OCTOBER 3, 2009
I agree with Eddie, except do TTF and OTF fonts all have EOT versions?   
I’m not sure, for example, you can find both a TTF and EOT version of the Calibri font. 

It looks like there’s a line command utility out there to [convert TTF and OTF fonts to EOT](http://tess.oconnor.cx/2009/07/how-to-create-eot-files-without-microsoft-weft) so that might be the best solution, but it sure seems like a chore.

### Chris says:
Permalink to comment# MAY 12, 2010
[fontsquirrel.com ](https://www.fontsquirrel.com/)allows you to upload a font (make sure the license allows this) and will then create the various versions of the font for you.

**Comment by jendiamond** [comment]
## Making some progress
Originally @Miilkytea added `config.assets.paths << Rails.root.join("app", "assets", "fonts")` to  `config/application.rb` at the very end, It needs to go where it is below. I included it and rans the Rails server and it returned no error.

**`config/application.rb`**
```ruby
require_relative 'boot'

require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
# require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module FeministAi
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
    config.assets.paths << Rails.root.join("app", "assets", "fonts")
  end
end
```

I also spent a lot of time converting the font with https://www.fontsquirrel.com/tools/webfont-generator

**Comment by jendiamond** [comment]
.woff stands for [Web Open Font Format](https://en.wikipedia.org/wiki/Web_Open_Font_Format)

WOFF is essentially a wrapper that contains SFNT-based fonts (TrueType or OpenType) that have been compressed using a WOFF encoding tool to enable them to be embedded in a Web page.

[Using fonts with Rails asset pipeline](http://stackoverflow.com/questions/10905905/using-fonts-with-rails-asset-pipeline)

Use your font in your css like you declared it in the font-family part. Since it was declared capitalized, you can use it like this:
#### `font-family: 'Icomoon';`

I did a test on the home page:  
`<h1 style="font-family: 'gt_americabold'; font-size:48px;" >GT America</h1>`
# SUCCESS!
![sucess](https://cloud.githubusercontent.com/assets/751697/24818630/2628dadc-1b96-11e7-8aa5-e80d034c094e.png)

# @Miilkytea the font is ready for you to use.
