### ISSUE TITLE
Update Collaborators

### ISSUE THREAD

**Issue by jendiamond** [BitsBytesAI/feminist_ai_projects#47]
### Commit https://github.com/BitsBytesAI/feminist_ai_projects/pull/52

**Comment by missmeinders** [comment]
A very special thanks to my academic advisor Elise Co! 

Direct or Indirect work on Feminist AI Projects Revisited has been made possible by emotional, intellectual and/or content contributions from the following feminists and organizations: Alison Adam, Sara Ahmed, Casey Anderson, Evelyn Arias, Erika Barbosa, Austin Beers, Adam Berros, Anne Burdick, Dara Blumenthal, Karen Ann Boren, Mary Jo Boren, Elizabeth Braithwaite, William Braithwaite, Don Brittain, Zachary Canter, Kelsey Carter, Rumman Chowdhury, Lee Cody, Stephanie Cedeno, Kora Colasuonno, Ivanna Coleman, Brittney Cottrell, Kate Crawford, Yvonne Cruz, Briana Dacoscos, Jen Diamond, Debra Do, Tim Durfee, Claire Evans, Rebecca Fiebrink, Laura Fisher, Shiveesh Fotedar, Damian Gill, Pamela Grieman, Noelle Griffis, Houston Guy, Donna Haraway, Katherine Hayles, Jean He, Shannon Herbert, Reichel Hertzler, Cathy Hillman, Leah Horgan, Yunqiao Huang, Nicholas Jayanty, Amanda Jensen, Casey Kawahara, Olive Kimono, Sonia Kissin, Lena Klimas, Liz Krane, Jesse Kriss, Hsinyu Lin, Marnie Maton , Maja Mataric, Joanne McNeil, Jade Milan, Tara Milch, Laura Montoya, Christopher Miles, Saara Nafici, Fay Nafici, Sohrab Nafici, Amirah Noaman, Claire Le Nobel, Camilla Pizarro, Jenny Rodenhouse, Lillian Rust, Suzanne Rust, RJ Sakai, Jen Samson, Camila Sobral, Ginny Song, Amanda Stojanov, Nan Tsai, Astha Vagadia, Philip van Allen, Michaella Vu, Emily Walworth, Sayee Wang, Lauren Williams, Jason Wong, Nicci Yin, Mimi Zeiger, Women Who Code, The Women’s Center for Creative Work, Cross Campus DTLA, The Altadena Public Library, Machine Project
