### ISSUE TITLE
Add Font Awesome Links to Social Media in Footer

### ISSUE THREAD

**Issue by jendiamond** [BitsBytesAI/feminist_ai_projects#5]
### Commit 1e7285214dc3fa45d2d13312015e4bf678c14f99

---

### Add links to Social media
https://github.com/bokmann/font-awesome-rails  
https://rubygems.org/gems/font-awesome-rails/versions/4.7.0.1  
`gem 'font-awesome-rails', '~> 4.7', '>= 4.7.0.1'`

http://www.rubydoc.info/gems/font-awesome-rails/4.7.0.1
**`app/assets/stylesheets/application.css.scss`**  
`@import "font-awesome";`

---

```
<%= link_to "<i class='fa fa-facebook' aria-hidden='true'></i>".html_safe, "https://www.facebook.com/ReimaginingBitsAndBytes/" -%>&nbsp;
<%= link_to "<i class='fa fa-twitter'  aria-hidden='true'></i>".html_safe, "https://twitter.com/bitsby-tes_la" -%>&nbsp;
<%= link_to "<i class='fa fa-calendar' aria-hidden='true'></i>".html_safe, events_path -%>&nbsp;
<%= link_to "<i class='fa fa-meetup'   aria-hidden='true'></i>".html_safe, "https://www.meetup.com/Bits-and-Bytes-Feminist-Artificial-Intelligence-Projects/" -%>&nbsp;
<%= link_to "<i class='fa fa-tumblr' aria-hidden='true'></i>".html_safe, "http://reimagin-
ing-bits-and-bytes.tumblr.com/" -%>&nbsp;
<%= link_to "<i class='fa fa-instagram' aria-hidden='true'></i>".html_safe, "https://www.instagram.com/bitsbytesai/" -%>
```

**Comment by jendiamond** [comment]
http://seegatesite.com/create-simple-cool-sidebar-menu-with-bootstrap-3/

**Comment by jendiamond** [comment]
+ Add Gem [gem 'simple_form', '~> 3.4'](https://rubygems.org/gems/simple_form/versions/3.4.0)
+ [Run the generator:](https://github.com/plataformatec/simple_form#installation)
    + rails generate simple_form:install --bootstrap

---

#### Change the forms  
```ruby
<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.button :submit %>
<% end %>
```

**Comment by BitsBytesAI** [comment]
Facebook:
https://www.facebook.com/ReimaginingBitsAndBytes/

Bits and Bytes github: BitsBytesAI

Bits and Bytes slack: bits--bytes.slack.com
e-mail christine.meinders@gmail.com to be added to the slack channel

Bits and Bytes tumblr: http://reimagin-
ing-bits-and-bytes.tumblr.com/

Bits and Bytes twitter: https://twitter.com/bitsby-tes_la
