### ISSUE TITLE
Change Text on Home page

### ISSUE THREAD

**Issue by jendiamond** [BitsBytesAI/feminist_ai_projects#9]
### Commit db99877ca8d3040a229eb12666ebef219d4da86b

**Comment by BitsBytesAI** [comment]
“Whereas the body can disappear into information with scarcely a murmur of protest, embodiment cannot, for it is tied to the circumstances of the occasion and the person.”

<b><i>How We Became Posthuman: Virtual Bodies in Cybernetics, Literature, and Informatics  
Katherine Hayles
